In [25]:
import gym
import numpy as np

In [ ]:
env = gym.make("MountainCar-v0")
env.reset()

learning_rate = 0.1
discount = 0.95
episodes = 25000


discrete_os_size = [20]*len(env.observation_space.high)
discrete_os_win_size = (env.observation_space.high-env.observation_space.low)/discrete_os_size
#print(discrete_os_size)
#print(discrete_os_win_size)
#print(env.observation_space.high)
#print(env.observation_space.low)
#print([20]*len(env.observation_space.high))

q_table = np.random.uniform(low =-2 , high=0 , size=(discrete_os_size+[env.action_space.n]))
#print(q_table.shape)

def get_discrete_state(state):
    discrete_state = (state-env.observation_space.low)/discrete_os_win_size
    return tuple(discrete_state.astype(np.int))

discrete_state = get_discrete_state(env.reset())

for episode in range(episodes) :
    




     done = False

     while not done :
        action =np.argmax(q_table[discrete_state])
        new_state , reward , done , _ = env.step(action)
        #print(new_state)

        new_discrete_state = get_discrete_state(new_state)
        #print(new_discrete_state)
        env.render()
        if not done:
            max_future_q = np.max(q_table[new_discrete_state])
            print(max_future_q)
            current_q = q_table[discrete_state+(action,)]
            print(current_q)
            new_q = (1-learning_rate) * current_q + learning_rate * (reward+discount*max_future_q)
            print(new_q)
            q_table[discrete_state+(action,)] = new_q
            print(q_table)
        elif new_state[0] >= env.goal_position :
            q_table[discrete_state+(action,)] = 0

        discrete_state = new_discrete_state    

     env.close()

-0.06862308827009311
-0.06862308827009311
-0.16827997282874266
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.617

[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.61738768 -0.30455493]
  [-1.80088798 -1.59571432 -1.91540806]]

 [

  [-1.04597541 -1.86225388 -0.71473113]]]
-0.9871586680191029
-0.9871586680191029
-1.0822228746790075
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.9988

  [-1.04597541 -1.86225388 -0.71473113]]]
-1.2807186931795
-1.2807186931795
-1.3743150997136027
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -

-0.9720862654018751
-0.9720862654018751
-1.0672258340748657
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.617387

-0.4955279146631038
-0.4955279146631038
-0.5930502750897884
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.617387

-0.8254100276029894
-0.8254100276029894
-0.9212829774649745
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.617387

-0.442316606846708
-0.442316606846708
-0.5401050238124745
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.61738768

[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.61738768 -0.30455493]
  [-1.80088798 -1.59571432 -1.91540806]]

 [

-1.064490475138613
-1.064490475138613
-1.15916802276292
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.61738768 -

-0.1984699465396147
-0.1984699465396147
-0.2974775968069166
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.617387

-1.3926222769178636
-1.4856591655332743
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.61738768 -0.30455493]
  [-

  [-1.04597541 -1.86225388 -0.71473113]]]
-1.1094850810493164
-1.1094850810493164
-1.20393765564407
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.998871

-0.8446009741987871
-0.342960153189617
-0.48890123041954003
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.617387

-1.2968869723138425
-1.2372101762187315
-1.3366934209666734
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.617387

-1.686076460281118
-1.686076460281118
-1.7776460779797123
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.61738768

-1.15916802276292
-1.15916802276292
-1.2533721826491053
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.61738768 -

-1.1408450261382184
-1.1408450261382184
-1.2351408010075273
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.617387

-1.7113494220738594
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.61738768 -0.30455493]
  [-1.80088798 -1.595714

  [-1.04597541 -1.86225388 -0.71473113]]]
-0.8713642617552847
-0.8998269032903708
-0.9926238178280858
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.9988

-1.3049957270428718
-0.5157236324204277
-0.6881258632474578
[[[-0.51940745 -1.46791958 -1.60022358]
  [-1.54112561 -1.06656029 -1.1530484 ]
  [-0.6271598  -0.78156868 -0.63006695]
  ...
  [-0.50512967 -1.51766844 -1.74807624]
  [-0.74261071 -0.15598834 -1.89355783]
  [-1.67465186 -1.66089225 -0.80163855]]

 [[-1.70209375 -1.93184069 -1.70356529]
  [-0.18649945 -0.13467085 -0.76295799]
  [-1.80119148 -0.93621042 -1.89869387]
  ...
  [-1.146692   -1.73504038 -0.4658559 ]
  [-0.19966846 -0.05579848 -1.99638584]
  [-1.17631292 -1.66798609 -0.65441451]]

 [[-0.07635196 -0.06695119 -0.38531541]
  [-1.27510636 -1.1030614  -1.86828405]
  [-0.59931494 -0.28172934 -0.46723275]
  ...
  [-0.16730789 -0.66187806 -0.82958588]
  [-1.86554421 -1.2604027  -1.02008273]
  [-0.23402276 -0.51422632 -0.91856713]]

 ...

 [[-0.38672291 -1.99517548 -1.22033854]
  [-1.20561359 -1.56768602 -1.84790963]
  [-1.58242441 -1.97954958 -0.08164407]
  ...
  [-1.91586657 -0.99887113 -0.53169615]
  [-0.87751161 -1.617387

In [ ]:
import gym
import numpy as np

env = gym.make("MountainCar-v0")

LEARNING_RATE = 0.1

DISCOUNT = 0.95
EPISODES = 25000
SHOW_EVERY = 10

DISCRETE_OS_SIZE = [20] * len(env.observation_space.high)
discrete_os_win_size = (env.observation_space.high - env.observation_space.low)/DISCRETE_OS_SIZE

# Exploration settings
epsilon = 1  # not a constant, qoing to be decayed
START_EPSILON_DECAYING = 1
END_EPSILON_DECAYING = EPISODES//2
epsilon_decay_value = epsilon/(END_EPSILON_DECAYING - START_EPSILON_DECAYING)


q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [env.action_space.n]))


def get_discrete_state(state):
    discrete_state = (state - env.observation_space.low)/discrete_os_win_size
    return tuple(discrete_state.astype(np.int))  # we use this tuple to look up the 3 Q values for the available actions in the q-table


for episode in range(EPISODES):
    discrete_state = get_discrete_state(env.reset())
    done = False

    if episode % SHOW_EVERY == 0:
        render = True
        print(episode)
    else:
        render = False

    while not done:

        if np.random.random() > epsilon:
            # Get action from Q table
            action = np.argmax(q_table[discrete_state])
        else:
            # Get random action
            action = np.random.randint(0, env.action_space.n)


        new_state, reward, done, _ = env.step(action)

        new_discrete_state = get_discrete_state(new_state)

        if episode % SHOW_EVERY == 0:
            env.render()
        #new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)

        # If simulation did not end yet after last step - update Q table
        if not done:

            # Maximum possible Q value in next step (for new state)
            max_future_q = np.max(q_table[new_discrete_state])

            # Current Q value (for current state and performed action)
            current_q = q_table[discrete_state + (action,)]

            # And here's our equation for a new Q value for current state and action
            new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)

            # Update Q table with new Q value
            q_table[discrete_state + (action,)] = new_q


        # Simulation ended (for any reson) - if goal position is achived - update Q value with reward directly
        elif new_state[0] >= env.goal_position:
            #q_table[discrete_state + (action,)] = reward
            q_table[discrete_state + (action,)] = 0

        discrete_state = new_discrete_state

    # Decaying is being done every episode if episode number is within decaying range
    if END_EPSILON_DECAYING >= episode >= START_EPSILON_DECAYING:
        epsilon -= epsilon_decay_value


env.close()



0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
